[versions]

# plugins
shadow = "9.3.0"
spotless = "8.1.0"
fabricLoom = "1.14.8"
legacyLoom = "1.14.1"

# libs
annotations = "26.0.2-1"
fabricLoader = "0.18.4"
cloudnet = "4.0.0-RC16-SNAPSHOT"
fabricMixin = "0.17.0+mixin.0.8.7"

[libraries]

annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
fabricMixin = { group = "net.fabricmc", name = "sponge-mixin", version.ref = "fabricMixin" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }

cloudnetDriver = { group = "eu.cloudnetservice.cloudnet", name = "driver-api", version.ref = "cloudnet" }
cloudnetBridge = { group = "eu.cloudnetservice.cloudnet", name = "bridge-impl", version.ref = "cloudnet" }
cloudnetWrapper = { group = "eu.cloudnetservice.cloudnet", name = "wrapper-jvm-api", version.ref = "cloudnet" }

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
legacyLoom = { id = "legacy-looming", version.ref = "legacyLoom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
fabricLoomNoRemap = { id = "net.fabricmc.fabric-loom", version.ref = "fabricLoom" }
fabricLoomRemap = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabricLoom" }
