[versions]

# plugins
shadow = "9.2.2"
spotless = "8.1.0"
fabricLoom = "1.12.7"
legacyLoom = "1.13.2"

# libs
annotations = "26.0.2-1"
fabricLoader = "0.17.0"
cloudnet = "4.0.0-RC16-SNAPSHOT"
fabricMixin = "0.16.5+mixin.0.8.7"

[libraries]

annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
fabricMixin = { group = "net.fabricmc", name = "sponge-mixin", version.ref = "fabricMixin" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }

cloudnetDriver = { group = "eu.cloudnetservice.cloudnet", name = "driver-api", version.ref = "cloudnet" }
cloudnetBridge = { group = "eu.cloudnetservice.cloudnet", name = "bridge-impl", version.ref = "cloudnet" }
cloudnetWrapper = { group = "eu.cloudnetservice.cloudnet", name = "wrapper-jvm-api", version.ref = "cloudnet" }

[plugins]

fabricLoom = { id = "fabric-loom", version.ref = "fabricLoom" }
legacyLoom = { id = "legacy-looming", version.ref = "legacyLoom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
